In [1]:
ls

drive/  sample_data/

In [2]:
cd '/content/drive/Shareddrives/CIS550/NBA stats'

/content/drive/Shareddrives/CIS550/NBA stats

In [61]:
import pandas as pd 
import numpy as np 
games= pd.read_csv('/content/drive/Shareddrives/CIS550/NBA stats/games.csv') 
games.head(5)
games = games.drop(['TEAM_ID_home', 'TEAM_ID_away'], axis =1)
games = games.dropna()
games = games.drop_duplicates(subset='GAME_ID', keep="first")

# games.loc[games['GAME_ID'] == 22000070]

games.to_csv('/content/drive/Shareddrives/CIS550/Processed data/games.csv')

In [74]:
games_details = pd.read_csv("/content/drive/Shareddrives/CIS550/NBA stats/games_details.csv")
games_details['START_POSITION'] = games_details['START_POSITION'].fillna('B')
games_details['COMMENT'] = games_details['COMMENT'].fillna('')
games_details['MIN'] = games_details['MIN'].fillna('')
games_details['MIN']= games_details['MIN'].astype(str)+ games_details['COMMENT'].astype(str)
games_details = games_details.drop(['TEAM_CITY', 'NICKNAME', 'COMMENT'], axis =1 )

games_details = games_details.drop_duplicates(subset=['TEAM_ID','GAME_ID', 'PLAYER_ID'], keep="first")


# games_details

games_details.to_csv('/content/drive/Shareddrives/CIS550/Processed data/games_details.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [47]:
player = pd.read_csv('/content/drive/Shareddrives/CIS550/NBA stats/players.csv')
player.head(5)

player.to_csv('/content/drive/Shareddrives/CIS550/Processed data/players.csv')

In [69]:
ranking =pd.read_csv("/content/drive/Shareddrives/CIS550/NBA stats/ranking.csv")
ranking.head(5)
ranking.drop(['LEAGUE_ID'], axis =1)
ranking["SEASON_ID"] = ranking["SEASON_ID"].astype(str).str.slice(1, 5)
ranking.head(5)

ranking = ranking.drop_duplicates(subset=['TEAM_ID','SEASON_ID', 'STANDINGSDATE'], keep="first")



# ranking.to_csv('/content/drive/Shareddrives/CIS550/Processed data/ranking.csv')

Empty DataFrame
Columns: [TEAM_ID, LEAGUE_ID, SEASON_ID, STANDINGSDATE, CONFERENCE, TEAM, G, W, L, W_PCT, HOME_RECORD, ROAD_RECORD, RETURNTOPLAY]
Index: []

In [53]:
teams = pd.read_csv("/content/drive/Shareddrives/CIS550/NBA stats/teams.csv")
teams =teams.drop(['LEAGUE_ID','MIN_YEAR','MAX_YEAR','ARENACAPACITY', 'DLEAGUEAFFILIATION'], axis= 1)
teams
# teams.to_csv('/content/drive/Shareddrives/CIS550/Processed data/teams.csv')

,TEAM_ID,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,OWNER,GENERALMANAGER,HEADCOACH
0,1610612737,ATL,Hawks,1949,Atlanta,State Farm Arena,Tony Ressler,Travis Schlenk,Lloyd Pierce
1,1610612738,BOS,Celtics,1946,Boston,TD Garden,Wyc Grousbeck,Danny Ainge,Brad Stevens
2,1610612740,NOP,Pelicans,2002,New Orleans,Smoothie King Center,Tom Benson,Trajan Langdon,Alvin Gentry
3,1610612741,CHI,Bulls,1966,Chicago,United Center,Jerry Reinsdorf,Gar Forman,Jim Boylen
4,1610612742,DAL,Mavericks,1980,Dallas,American Airlines Center,Mark Cuban,Donnie Nelson,Rick Carlisle
5,1610612743,DEN,Nuggets,1976,Denver,Pepsi Center,Stan Kroenke,Tim Connelly,Michael Malone
6,1610612745,HOU,Rockets,1967,Houston,Toyota Center,Tilman Fertitta,Daryl Morey,Mike D'Antoni
7,1610612746,LAC,Clippers,1970,Los Angeles,Staples Center,Steve Ballmer,Michael Winger,Doc Rivers
8,1610612747,LAL,Lakers,1948,Los Angeles,Staples Center,Jerry Buss Family Trust,Rob Pelinka,Frank Vogel
9,1610612748,MIA,Heat,1988,Miami,AmericanAirlines Arena,Micky Arison,Pat Riley,Erik Spoelstra
10,1610612749,MIL,Bucks,1968,Milwaukee,Fiserv Forum,Wesley Edens & Marc Lasry,Jon Horst,Mike Budenholzer
11,1610612750,MIN,Timberwolves,1989,Minnesota,Target Center,Glen Taylor,Scott Layden,Ryan Saunders
12,1610612751,BKN,Nets,1976,Brooklyn,Barclays Center,Joe Tsai,Sean Marks,Kenny Atkinson
13,1610612752,NYK,Knicks,1946,New York,Madison Square Garden,Cablevision (James Dolan),Steve Mills,David Fizdale
14,1610612753,ORL,Magic,1989,Orlando,Amway Center,Rick DeVos,John Hammond,Steve Clifford
15,1610612754,IND,Pacers,1976,Indiana,Bankers Life Fieldhouse,Herb Simon,Kevin Pritchard,Nate McMillan
16,1610612755,PHI,76ers,1949,Philadelphia,Wells Fargo Center,Joshua Harris,Elton Brand,Brett Brown
17,1610612756,PHX,Suns,1968,Phoenix,Talking Stick Resort Arena,Robert Sarver,James Jones,Monty Williams
18,1610612757,POR,Trail Blazers,1970,Portland,Moda Center,Paul Allen,Neil Olshey,Terry Stotts
19,1610612758,SAC,Kings,1948,Sacramento,Golden 1 Center,Vivek Ranadive,Vlade Divac,Luke Walton
20,1610612759,SAS,Spurs,1976,San Antonio,AT&T Center,Peter Holt,Brian Wright,Gregg Popovich
21,1610612760,OKC,Thunder,1967,Oklahoma City,Chesapeake Energy Arena,Clay Bennett,Sam Presti,Billy Donovan
22,1610612761,TOR,Raptors,1995,Toronto,Scotiabank Arena,Maple Leaf Sports and Entertainment,Masai Ujiri,Nick Nurse
23,1610612762,UTA,Jazz,1974,Utah,Vivint Smart Home Arena,Greg Miller,Dennis Lindsey,Quin Snyder
24,1610612763,MEM,Grizzlies,1995,Memphis,FedExForum,Robert Pera,Zach Kleiman,Taylor Jenkins
25,1610612764,WAS,Wizards,1961,Washington,Capital One Arena,Ted Leonsis,Tommy Sheppard,Scott Brooks
26,1610612765,DET,Pistons,1948,Detroit,Little Caesars Arena,Tom Gores,Ed Stefanski,Dwane Casey
27,1610612766,CHA,Hornets,1988,Charlotte,Spectrum Center,Michael Jordan,Mitch Kupchak,James Borrego
28,1610612739,CLE,Cavaliers,1970,Cleveland,Quicken Loans Arena,Dan Gilbert,Koby Altman,John Beilein
29,1610612744,GSW,Warriors,1946,Golden State,Chase Center,Joe Lacob,Bob Myers,Steve Kerr